name = "cloudaccount-app"
main = "terraform/worker.js"
compatibility_date = "2023-09-01"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "CLOUDACCOUNT_DB"
database_id = ""  # Will be filled by the CI/CD pipeline

[triggers]
crons = ["0 */6 * * *"]  # Run currency rate updates every 6 hours