name: Deploy Worker with Wrangler

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
    paths:
      - 'server/worker.ts'
      - '.github/workflows/deploy-worker.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create Worker Module File
        run: |
          # First compile the TypeScript worker to JavaScript
          npx tsc --target ES2022 --module ESNext --outDir ./dist server/worker.ts
          
          # Copy the compiled file to the correct location
          cp ./dist/server/worker.js ./worker.js
          
          # Verify the worker has proper ESM export syntax
          if ! grep -q "export default" ./worker.js; then
            echo "Error: worker.js does not contain ESM export syntax"
            exit 1
          fi
          
          # Create minimal wrangler.toml for deployment
          cat > wrangler-deploy.toml << EOF
          name = "mtd-itsa-prototype"
          main = "worker.js"
          compatibility_date = "2024-01-01"
          
          # Explicitly set module format
          type = "javascript"
          format = "modules"
          
          # D1 database binding
          [[d1_databases]]
          binding = "DB"
          database_name = "mtd_itsa_db"
          database_id = "${{ secrets.CF_D1_DATABASE_ID }}"
          EOF

      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler deploy --config wrangler-deploy.toml